default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username:
  password:
  host: localhost

development:
  <<: *default
  database: contact_list_development

test:
  <<: *default
  database: contact_list_test

production:
  <<: *default
  database: contact_list_production
  username: seu_usuario
  password: sua_senha
